site_name: Ayush Cool Writings
site_url: https://www.ayush-writings-space.com/
site_description: Project documentation with Markdown.
site_author: Ayush Saxena

repo_url: https://github.com/ayush78781/Ayush-Writings-Space/
edit_uri: blob/main/docs/

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Initiatives: 'initiatives.md'
    - License: 'license.md'
    - Products: 'products.md'
    - Services: 'services.md'
    - User Guide: 
       - Getting Started: 'user-guide/getting-started.md'
       - Contribuiting Guidelines: 'user-guide/contributing-guidelines.md'

markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    site_name: 'logo.jpg'
    locale: en

copyright: Copyright &copy; 2023 <a href="https://twitter.com/">Ayush Saxena</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Ayush's Space</a>.
